### ISSUE TITLE
Mandated WGS84 with no date/time requirement

### ISSUE THREAD

**Issue by Chaz6** [geojson/draft-geojson#76] opened 2015-06-09 15:42 UTC
If the spec mandates WGS84, then it should also mandate date/time for each coordinate, otherwise geojson files can only be used for short-term throwaway datasets, since accuracy and longevity are impaired. Using my local crs (OSGB36) I know that coordinates drift far far less since it is locked to the European plate, but WGS84 coordinates will constantly drift.

I am opposed to removing support for crs. Please maintain support for crs, and preferably it should be a mandated attribute.

**Comment by sgillies** [comment] 2015-06-09 17:00
GeoJSON was designed for use in messages on the internet and has relied on protocols (like HTTP) or version control systems (like Git) for timestamps. It might be good for the format to address metadata more directly, it's true. Are you suggesting that all geometries would be timestamped or do you have a different idea?

The problems with supporting every CRS in the world (as discussed elsewhere in this issue tracker and on the old mailing list) are that 1) GeoJSON did it poorly in the past and that 2) a single coordinate reference system standard makes the internet work better in the same way that a single calendar system standard [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) makes the internet work better.

**Comment by jyutzler** [comment] 2015-06-09 17:01
Please note that this is a much more complex topic than it might seem on the surface. See #30, #36, #37. The wording in Sections 3 and 6 was carefully crafted to appease all sides. The specification allows you to use other CRSs but this is not recommended because there is no guarantee that any particular client application will interpret them properly. In other words, do what you need to do but be careful.

**Comment by dret** [comment] 2015-06-10 07:56
out of curiosity: having one timestamp per coordinate feels like it might add a lot of redundancy. is there a reason why you wouldn't want to have timestamps at a higher level?

**Comment by skj3gg** [comment] 2015-06-11 00:01
@dret One reason could be a collection of geometries showing the same geometries dimensions over time?

**Comment by dret** [comment] 2015-06-11 06:05
i am sure there are scenarios where per-geometry or per-coordinate timestamps would help, but i was mostly trying to figure out in how many cases a more coarse-grained timestamp might be good enough. if we have per-coordinate timestamps, GeoJSON starts looking like GPX or TCX (a bit), right?

**Comment by chris-little** [comment] 2015-06-18 15:40
Sorry to sound pedantic, but I just wanted to warn against calling RFC 3339 anything other than a timestamp standard. It is not a calendar or temporal CRS standard. As Jeff Y says, It is very carefully crafted to ensure its timestamps can be placed in an unambiguous montonic order, and thus perform rigorous logical operations (before, after, between, etc) but there is no guarantee of being able to calculate durations consistently to one second precision. E.g. ISO8601 states that leap seconds are included in calculations, whereas JavaScript (ECMA-262 5.1 Edition June 2011) states ignore them.

**Comment by Chaz6** [comment] 2015-06-24 06:56
If the spec was to mandate WGS84 then yes I would wish to associate a timestamp with every feature. Doing it at the layer-level will at least provide some coarse accuracy information which is better than none.

**Comment by jyutzler** [comment] 2015-06-24 16:44
@Chaz6 I don't like the word "mandate" in this context. The GeoJSON specification is _mostly_ about setting expectations of what GeoJSON consumers will understand as opposed to telling people what they can and can't do. You don't have to use WGS84 and there is a mechanism to declare an alternate CRS if you have the need to do so. However, consider yourself warned - many (most?) consumers won't understand it. If you want to do something that falls outside the spec and is just for your domain, just do it. Unless it specifically violates something in the spec, no one will mind.

**Comment by sgillies** [comment] 2015-07-17 15:56
Closing this as I don't see any action coming out of the discussion.

**Closed by sgillies** 2015-07-17 15:56 UTC
